In [ ]:
import tensorflow as tf

print("=== BÀI 1 ===")
A = tf.zeros([2, 3])
print(A)


print("\n=== BÀI 2 ===")
X = tf.constant([[1, 2, 3], [4, 5, 6]])
zero_tensor = tf.zeros_like(X)
print(zero_tensor)


print("\n=== BÀI 3 ===")
Y = tf.fill([3, 2], 5)
print(Y)


print("\n=== BÀI 4 ===")
Z = tf.linspace(5, 10, 50)
print(Z)


print("\n=== BÀI 5 ===")
C = tf.range(10, 101, delta=2)
print(C)


print("\n=== BÀI 6 ===")
V = tf.random.normal([3, 2], mean=0, stddev=2)
print(V)


print("\n=== BÀI 7 ===")
B = tf.random.uniform([3, 2], minval=0, maxval=2)
print(B)


print("\n=== BÀI 8 ===")
X = tf.constant([[1, 2], [3, 4], [5, 6]])
print("Before shuffle:\n", X)
print("After shuffle:\n", tf.random.shuffle(X))


print("\n=== BÀI 9 ===")
N = tf.random.uniform((10, 10, 3))
cropped = tf.image.random_crop(N, size=(5, 5, 3))
print("Original:", N.shape)
print("Cropped:", cropped.shape)


print("\n=== BÀI 10 ===")
x = tf.random.uniform((5,), minval=0, maxval=10)
y = tf.random.uniform((5,), minval=0, maxval=10)
result = tf.where(x < y, x + y, x - y)
print("x:", x.numpy())
print("y:", y.numpy())
print("result:", result.numpy())


print("\n=== BÀI 11 ===")
x = tf.random.uniform((3, 2), minval=5, maxval=10)
y = tf.random.uniform((2, 3), minval=15, maxval=20)

x_diag = tf.linalg.band_part(x, 0, 0)
y_T = tf.transpose(y)

result = x_diag + y_T

print("x:\n", x.numpy())
print("x_diag:\n", x_diag.numpy())
print("y_T:\n", y_T.numpy())
print("result:\n", result.numpy())


print("\n=== BÀI 12 ===")

def create_tensors():
    x = tf.random.uniform((3, 2, 2))
    y = tf.random.uniform((3, 2, 2))
    return x, y

@tf.function
def add(x, y): return x + y

@tf.function
def sub(x, y): return x - y

@tf.function
def mul(x, y): return x * y

@tf.function
def div(x, y): return x / y

x, y = create_tensors()
print("Add:\n", add(x, y))


print("\n=== BÀI 13 ===")

x_in = tf.keras.Input(shape=(3, 2, 2))
y_in = tf.keras.Input(shape=(3, 2, 2))
model_13 = tf.keras.Model([x_in, y_in], x_in + y_in)

x_val = tf.random.uniform((1, 3, 2, 2))
y_val = tf.random.uniform((1, 3, 2, 2))

print(model_13([x_val, y_val]))


print("\n=== BÀI 14 ===")

x_in = tf.keras.Input(shape=(3, 2, 2))
y_in = tf.keras.Input(shape=(3, 2, 2))

model_14 = tf.keras.Model([x_in, y_in], [x_in - y_in, x_in * y_in])

sub_res, mul_res = model_14([x_val, y_val])
print("Sub:\n", sub_res)
print("Mul:\n", mul_res)


print("\n=== BÀI 15 ===")

a = tf.keras.Input(shape=())
b = tf.keras.Input(shape=())

model_15 = tf.keras.Model([a, b], 2 * (a + b))

print(model_15([tf.constant([3.0]), tf.constant([4.0])]))


print("\n=== BÀI 16 ===")

a = tf.keras.Input(shape=())
b = tf.keras.Input(shape=())
c = tf.keras.Input(shape=())

Sxq = 2 * (a + b) * c
Stp = 2 * (a * b) + Sxq

model_16 = tf.keras.Model([a, b, c], [Sxq, Stp])

print(model_16([
    tf.constant([2.0]),
    tf.constant([3.0]),
    tf.constant([4.0])
]))


print("\n=== BÀI 17 ===")

from tensorflow.keras.layers import Lambda

a1 = tf.keras.Input(shape=())
a2 = tf.keras.Input(shape=())
b1 = tf.keras.Input(shape=())
b2 = tf.keras.Input(shape=())

cross = a1 * b2 - a2 * b1
parallel = Lambda(lambda x: tf.abs(x) < 1e-6)(cross)

model_17 = tf.keras.Model([a1, a2, b1, b2], parallel)

print(model_17([
    tf.constant([1.0]), tf.constant([2.0]),
    tf.constant([2.0]), tf.constant([4.0])
]))


print("\n=== BÀI 18 ===")

a = tf.keras.Input(shape=())
b = tf.keras.Input(shape=())

equal = Lambda(lambda x: tf.abs(x[0] - x[1]) < 1e-6)([a, b])
model_18 = tf.keras.Model([a, b], equal)

print(model_18([tf.constant([5.0]), tf.constant([5.0])]))


print("\n=== BÀI 19 ===")

AM = tf.keras.Input(shape=())
MB = tf.keras.Input(shape=())
AN = tf.keras.Input(shape=())
NC = tf.keras.Input(shape=())

NA = AM + AN
NC_val = MB + NC

equal = Lambda(lambda x: tf.abs(x[0] - x[1]) < 1e-6)([NA, NC_val])

model_19 = tf.keras.Model([AM, MB, AN, NC], equal)

print(model_19([
    tf.constant([2.0]),
    tf.constant([1.0]),
    tf.constant([3.0]),
    tf.constant([4.0])
]))

=== BÀI 1 ===
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)

=== BÀI 2 ===
tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)

=== BÀI 3 ===
tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)

=== BÀI 4 ===
tf.Tensor(
[ 5.          5.10204082  5.20408163  5.30612245  5.40816327  5.51020408
  5.6122449   5.71428571  5.81632653  5.91836735  6.02040816  6.12244898
  6.2244898   6.32653061  6.42857143  6.53061224  6.63265306  6.73469388
  6.83673469  6.93877551  7.04081633  7.14285714  7.24489796  7.34693878
  7.44897959  7.55102041  7.65306122  7.75510204  7.85714286  7.95918367
  8.06122449  8.16326531  8.26530612  8.36734694  8.46938776  8.57142857
  8.67346939  8.7755102   8.87755102  8.97959184  9.08163265  9.18367347
  9.28571429  9.3877551   9.48979592  9.59183673  9.69387755  9.79591837
  9.89795918 10.        ], shape=(50,), dtype=float64)

=== BÀI 5 ===
tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  4